#!/bin/bash
# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

set -e

cat >setup.txt <<EOL
$RASPI_USER
$RASPI_PWD

env IOTHUB_CONNECTION_STRING=$IOTHUB_CONNECTION_STRING
env IOTHUB_EVENTHUB_CONNECTION_STRING=$IOTHUB_EVENTHUB_CONNECTION_STRING
env IOTHUB_PARTITION_COUNT=16
env IOTHUB_E2E_X509_CERT_BASE64=$IOTHUB_E2E_X509_CERT_BASE64
env IOTHUB_E2E_X509_PRIVATE_KEY_BASE64=$IOTHUB_E2E_X509_PRIVATE_KEY_BASE64
env IOTHUB_E2E_X509_THUMBPRINT=$IOTHUB_E2E_X509_THUMBPRINT
env IOTHUB_POLICY_KEY=$IOTHUB_POLICY_KEY

env IOT_DPS_CONNECTION_STRING=$IOT_DPS_CONNECTION_STRING
env IOT_DPS_ID_SCOPE=$IOT_DPS_ID_SCOPE
env IOTHUB_CA_ROOT_CERT=$IOTHUB_CA_ROOT_CERT
env IOTHUB_CA_ROOT_CERT_KEY=$IOTHUB_CA_ROOT_CERT_KEY
env IOT_DPS_GLOBAL_ENDPOINT=$IOT_DPS_GLOBAL_ENDPOINT
env IOTHUB_DEVICE_CONN_STRING_INVALIDCERT=$IOTHUB_DEVICE_CONN_STRING_INVALIDCERT
env IOTHUB_CONN_STRING_INVALIDCERT=$IOTHUB_CONN_STRING_INVALIDCERT
env DPS_GLOBALDEVICEENDPOINT_INVALIDCERT=$DPS_GLOBALDEVICEENDPOINT_INVALIDCERT
env PROVISIONING_CONNECTION_STRING_INVALIDCERT=$PROVISIONING_CONNECTION_STRING_INVALIDCERT

EOL
