#!/bin/bash
# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

set -e

cat >setup.txt <<EOL
IOTHUB_EVENTHUB_CONNECTION_STRING=$IOTHUB_EVENTHUB_CONNECTION_STRING
IOTHUB_EVENTHUB_CONSUMER_GROUP=$Default
IOTHUB_PARTITION_COUNT=16
IOTHUB_E2E_X509_CERT_BASE64=$IOTHUB_E2E_X509_CERT_BASE64
IOTHUB_E2E_X509_PRIVATE_KEY_BASE64=$IOTHUB_E2E_X509_PRIVATE_KEY_BASE64
IOTHUB_E2E_X509_THUMBPRINT=$IOTHUB_E2E_X509_THUMBPRINT
EOL

# basic setup of input script for python
# echo -e "IOTHUB_EVENTHUB_CONNECTION_STRING=$IOTHUB_EVENTHUB_CONNECTION_STRING\n$RASPI_PWD\nsz -a $RASPI_TEST_FILE > $RASPI_PORT < $RASPI_PORT\n\n$RASPI_SERIAL_TASK\n\n" | cat > input.txt
