# CMake generated Testfile for 
# Source directory: C:/code/s1/azure-iot-sdk-c-pr2720-clean/iothub_client/tests
# Build directory: C:/code/s1/azure-iot-sdk-c-pr2720-clean/build_local/iothub_client/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("iothub_ut")
subdirs("iothub_client_authorization_ut")
subdirs("iothub_transport_ll_private_ut")
subdirs("iothubclient_ll_ut")
subdirs("iothubclientcore_ll_ut")
subdirs("iothubclient_diagnostic_ut")
subdirs("iothubdeviceclient_ll_ut")
subdirs("iothubclient_ll_u2b_ut")
subdirs("blob_ut")
subdirs("iothubclient_ut")
subdirs("iothubclientcore_ut")
subdirs("iothubdeviceclient_ut")
subdirs("iothubmessage_ut")
subdirs("iothubtransport_ut")
subdirs("iothub_client_properties_ut")
subdirs("iothub_client_retry_control_ut")
subdirs("message_queue_ut")
subdirs("iothubmoduleclient_ll_ut")
subdirs("iothubmoduleclient_ut")
subdirs("iothubtransporthttp_ut")
subdirs("iothubtransportmqtt_ut")
subdirs("iothubtransport_mqtt_common_ut")
subdirs("iothubtransport_mqtt_common_int_ut")
subdirs("iothubtransportmqtt_ws_ut")
subdirs("uamqp_messaging_ut")
subdirs("iothubtransport_amqp_common_ut")
subdirs("iothubtransport_amqp_device_ut")
subdirs("iothubtransport_amqp_cbs_auth_ut")
subdirs("iothubtransportamqp_methods_ut")
subdirs("iothubtransport_amqp_connection_ut")
subdirs("iothubtr_amqp_tel_msgr_ut")
subdirs("iothubtr_amqp_msgr_ut")
subdirs("iothubtr_amqp_twin_msgr_ut")
subdirs("iothubtransportamqp_ut")
subdirs("iothubtransportamqp_ws_ut")
subdirs("version_ut")
