/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/digitalTwinMappers";
import * as Parameters from "../models/parameters";
import { IotHubGatewayServiceAPIs20190701PreviewContext } from "../iotHubGatewayServiceAPIs20190701PreviewContext";

/** Class representing a DigitalTwin. */
export class DigitalTwin {
  private readonly client: IotHubGatewayServiceAPIs20190701PreviewContext;

  /**
   * Create a DigitalTwin.
   * @param {IotHubGatewayServiceAPIs20190701PreviewContext} client Reference to the service client.
   */
  constructor(client: IotHubGatewayServiceAPIs20190701PreviewContext) {
    this.client = client;
  }

  /**
   * @summary Gets the properties of interfaces.
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinGetAllInterfacesResponse>
   */
  getAllInterfaces(digitalTwinId: string, options?: msRest.RequestOptionsBase): Promise<Models.DigitalTwinGetAllInterfacesResponse>;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param callback The callback
   */
  getAllInterfaces(digitalTwinId: string, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param options The optional parameters
   * @param callback The callback
   */
  getAllInterfaces(digitalTwinId: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  getAllInterfaces(digitalTwinId: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DigitalTwinInterfaces>, callback?: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): Promise<Models.DigitalTwinGetAllInterfacesResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        options
      },
      getAllInterfacesOperationSpec,
      callback) as Promise<Models.DigitalTwinGetAllInterfacesResponse>;
  }

  /**
   * @summary Updates desired properties of multiple interfaces.
   * Example URI: "digitalTwins/{digitalTwinId}/interfaces"
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param interfacesPatchInfo Multiple interfaces desired properties to update.
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinUpdateMultipleInterfacesResponse>
   */
  updateMultipleInterfaces(digitalTwinId: string, interfacesPatchInfo: Models.DigitalTwinInterfacesPatch, options?: Models.DigitalTwinUpdateMultipleInterfacesOptionalParams): Promise<Models.DigitalTwinUpdateMultipleInterfacesResponse>;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param interfacesPatchInfo Multiple interfaces desired properties to update.
   * @param callback The callback
   */
  updateMultipleInterfaces(digitalTwinId: string, interfacesPatchInfo: Models.DigitalTwinInterfacesPatch, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param interfacesPatchInfo Multiple interfaces desired properties to update.
   * @param options The optional parameters
   * @param callback The callback
   */
  updateMultipleInterfaces(digitalTwinId: string, interfacesPatchInfo: Models.DigitalTwinInterfacesPatch, options: Models.DigitalTwinUpdateMultipleInterfacesOptionalParams, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  updateMultipleInterfaces(digitalTwinId: string, interfacesPatchInfo: Models.DigitalTwinInterfacesPatch, options?: Models.DigitalTwinUpdateMultipleInterfacesOptionalParams | msRest.ServiceCallback<Models.DigitalTwinInterfaces>, callback?: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): Promise<Models.DigitalTwinUpdateMultipleInterfacesResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        interfacesPatchInfo,
        options
      },
      updateMultipleInterfacesOperationSpec,
      callback) as Promise<Models.DigitalTwinUpdateMultipleInterfacesResponse>;
  }

  /**
   * @summary Gets the properties of given interface.
   * Example URI: "digitalTwins/{digitalTwinId}/interfaces/{interfaceName}"
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param interfaceName Interface name, for example <example>myThermostat</example>.
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinGetSingleInterfaceResponse>
   */
  getSingleInterface(digitalTwinId: string, interfaceName: string, options?: msRest.RequestOptionsBase): Promise<Models.DigitalTwinGetSingleInterfaceResponse>;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param interfaceName Interface name, for example <example>myThermostat</example>.
   * @param callback The callback
   */
  getSingleInterface(digitalTwinId: string, interfaceName: string, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param interfaceName Interface name, for example <example>myThermostat</example>.
   * @param options The optional parameters
   * @param callback The callback
   */
  getSingleInterface(digitalTwinId: string, interfaceName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): void;
  getSingleInterface(digitalTwinId: string, interfaceName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DigitalTwinInterfaces>, callback?: msRest.ServiceCallback<Models.DigitalTwinInterfaces>): Promise<Models.DigitalTwinGetSingleInterfaceResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        interfaceName,
        options
      },
      getSingleInterfaceOperationSpec,
      callback) as Promise<Models.DigitalTwinGetSingleInterfaceResponse>;
  }

  /**
   * Invoke a digital twin interface command.
   * @summary Invoke a digital twin interface command.
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param interfaceName Interface name, for example <example>myThermostat</example>.
   * @param commandName
   * @param payload
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinInvokeInterfaceCommandResponse>
   */
  invokeInterfaceCommand(digitalTwinId: string, interfaceName: string, commandName: string, payload: any, options?: Models.DigitalTwinInvokeInterfaceCommandOptionalParams): Promise<Models.DigitalTwinInvokeInterfaceCommandResponse>;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param interfaceName Interface name, for example <example>myThermostat</example>.
   * @param commandName
   * @param payload
   * @param callback The callback
   */
  invokeInterfaceCommand(digitalTwinId: string, interfaceName: string, commandName: string, payload: any, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param digitalTwinId Digital Twin ID. Format of digitalTwinId is DeviceId[~ModuleId]. ModuleId
   * is optional.
   * Example 1: "myDevice"
   * Example 2: "myDevice~module1"
   * @param interfaceName Interface name, for example <example>myThermostat</example>.
   * @param commandName
   * @param payload
   * @param options The optional parameters
   * @param callback The callback
   */
  invokeInterfaceCommand(digitalTwinId: string, interfaceName: string, commandName: string, payload: any, options: Models.DigitalTwinInvokeInterfaceCommandOptionalParams, callback: msRest.ServiceCallback<any>): void;
  invokeInterfaceCommand(digitalTwinId: string, interfaceName: string, commandName: string, payload: any, options?: Models.DigitalTwinInvokeInterfaceCommandOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.DigitalTwinInvokeInterfaceCommandResponse> {
    return this.client.sendOperationRequest(
      {
        digitalTwinId,
        interfaceName,
        commandName,
        payload,
        options
      },
      invokeInterfaceCommandOperationSpec,
      callback) as Promise<Models.DigitalTwinInvokeInterfaceCommandResponse>;
  }

  /**
   * @summary Returns a DigitalTwin model definition for the given "id".
   * If "expand" is present in the query parameters and "id" is for a device capability model then it
   * returns
   * the capability metamodel with expanded interface definitions.
   * @param modelId Model id Ex: <example>urn:contoso:TemperatureSensor:1</example>
   * @param [options] The optional parameters
   * @returns Promise<Models.DigitalTwinGetDigitalTwinModelResponse>
   */
  getDigitalTwinModel(modelId: string, options?: Models.DigitalTwinGetDigitalTwinModelOptionalParams): Promise<Models.DigitalTwinGetDigitalTwinModelResponse>;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:TemperatureSensor:1</example>
   * @param callback The callback
   */
  getDigitalTwinModel(modelId: string, callback: msRest.ServiceCallback<any>): void;
  /**
   * @param modelId Model id Ex: <example>urn:contoso:TemperatureSensor:1</example>
   * @param options The optional parameters
   * @param callback The callback
   */
  getDigitalTwinModel(modelId: string, options: Models.DigitalTwinGetDigitalTwinModelOptionalParams, callback: msRest.ServiceCallback<any>): void;
  getDigitalTwinModel(modelId: string, options?: Models.DigitalTwinGetDigitalTwinModelOptionalParams | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.DigitalTwinGetDigitalTwinModelResponse> {
    return this.client.sendOperationRequest(
      {
        modelId,
        options
      },
      getDigitalTwinModelOperationSpec,
      callback) as Promise<Models.DigitalTwinGetDigitalTwinModelResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getAllInterfacesOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "digitalTwins/{digitalTwinId}/interfaces",
  urlParameters: [
    Parameters.digitalTwinId
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: Mappers.DigitalTwinInterfaces,
      headersMapper: Mappers.DigitalTwinGetAllInterfacesHeaders
    },
    default: {}
  },
  serializer
};

const updateMultipleInterfacesOperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "digitalTwins/{digitalTwinId}/interfaces",
  urlParameters: [
    Parameters.digitalTwinId
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.ifMatch
  ],
  requestBody: {
    parameterPath: "interfacesPatchInfo",
    mapper: {
      ...Mappers.DigitalTwinInterfacesPatch,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.DigitalTwinInterfaces,
      headersMapper: Mappers.DigitalTwinUpdateMultipleInterfacesHeaders
    },
    default: {}
  },
  serializer
};

const getSingleInterfaceOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "digitalTwins/{digitalTwinId}/interfaces/{interfaceName}",
  urlParameters: [
    Parameters.digitalTwinId,
    Parameters.interfaceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: Mappers.DigitalTwinInterfaces,
      headersMapper: Mappers.DigitalTwinGetSingleInterfaceHeaders
    },
    default: {}
  },
  serializer
};

const invokeInterfaceCommandOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "digitalTwins/{digitalTwinId}/interfaces/{interfaceName}/commands/{commandName}",
  urlParameters: [
    Parameters.digitalTwinId,
    Parameters.interfaceName,
    Parameters.commandName
  ],
  queryParameters: [
    Parameters.responseTimeoutInSeconds,
    Parameters.connectTimeoutInSeconds,
    Parameters.apiVersion
  ],
  requestBody: {
    parameterPath: "payload",
    mapper: {
      required: true,
      serializedName: "payload",
      type: {
        name: "Object"
      }
    }
  },
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      },
      headersMapper: Mappers.DigitalTwinInvokeInterfaceCommandHeaders
    },
    default: {}
  },
  serializer
};

const getDigitalTwinModelOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "digitalTwins/models/{modelId}",
  urlParameters: [
    Parameters.modelId
  ],
  queryParameters: [
    Parameters.expand,
    Parameters.apiVersion
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      },
      headersMapper: Mappers.DigitalTwinGetDigitalTwinModelHeaders
    },
    default: {}
  },
  serializer
};
