# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'AzureIoTSampleWorkspace'

target 'AzureIoTSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AzureIoTSample
  pod 'AzureIoTUtility'
  pod 'AzureIoTuMqtt'
  pod 'AzureIoTuAmqp'
  pod 'AzureIoTHubClient'
end
