// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.


/** @file    iothub_client_properties.h.h
*   @brief   APIs that serialize and deserialize properties to and from IoT Hub.
*/

#ifndef IOTHUB_CLIENT_PROPERTIES_H
#define IOTHUB_CLIENT_PROPERTIES_H

#include "iothub_client_core_common.h"

/** @brief Current version of @p IOTHUB_CLIENT_REPORTED_PROPERTY structure.  */
#define IOTHUB_CLIENT_REPORTED_PROPERTY_VERSION_1 1

/** @brief    This struct defines properties reported from the device.  This corresponds to what DTDLv2 calls a "read-only property." */
typedef struct IOTHUB_CLIENT_REPORTED_PROPERTY_TAG {
    /** @brief   Version of the structure.  Currently must be IOTHUB_CLIENT_REPORTED_PROPERTY_VERSION_1. */
    int version;
    /** @brief    The name of the property. */
    const char* name;
    /** @brief    The value of the property. */
    const char* value;
} IOTHUB_CLIENT_REPORTED_PROPERTY;

/** @brief Current version of @p IOTHUB_CLIENT_WRITEABLE_PROPERTY_RESPONSE structure.  */
#define IOTHUB_CLIENT_WRITEABLE_PROPERTY_RESPONSE_VERSION_1 1

/** @brief    This struct represents the response to a writeable property that the device will return.  
              This structure is filled out by the application and can be serialized into a payload for the network via IoTHubClient_Serialize_WriteablePropertyResponse. */
typedef struct IOTHUB_CLIENT_WRITEABLE_PROPERTY_RESPONSE_TAG {
    /** @brief   Version of the structure.  Currently must be IOTHUB_CLIENT_REPORTED_PROPERTY_VERSION_1. */
    int version;
    /** @brief Name of the property. */
    const char* name;
    /** @brief Value of the property. */
    const char* value;
    /** @brief Result of the requested operation.  This maps to an HTTP status code.  */
    int result;
    /** @brief Acknowledgement version.  This corresponds to the version of the writeable properties being responded to. */
    int ackVersion;
    /** @brief Optional friendly description of the operation.  May be NULL. */
    const char* description;
} IOTHUB_CLIENT_WRITEABLE_PROPERTY_RESPONSE;

// Use constructor thingy

/** @brief Enumeration that indicates whether a given property from the service was originally reported from the device
           (and hence the device application sees what the last reported value IoT Hub has)
           or whether this is a writeable property that the service is requesting configuration for.
*/
typedef enum IOTHUB_PROPERTY_TYPE_TAG 
{
    /** @brief Property was initially reported from the device. */
    IOTHUB_CLIENT_PROPERTY_TYPE_REPORTED_FROM_DEVICE,
    /** @brief Property is writeable.  It is configured by service remotely. */
    IOTHUB_CLIENT_PROPERTY_TYPE_WRITEABLE
} IOTHUB_CLIENT_PROPERTY_TYPE;


/** @brief Current version of @p IOTHUB_CLIENT_DESERIALIZED_PROPERTY structure.  */
#define IOTHUB_CLIENT_DESERIALIZED_PROPERTY_VERSION 1

/** @brief    This struct represents a property from the service.  
              It is generated by IoTHubClient_Deserialize_Properties while deserializing a property payload. */
typedef struct IOTHUB_CLIENT_DESERIALIZED_PROPERTY_TAG {
    /** @brief   Version of the structure.  Currently must be IOTHUB_CLIENT_DESERIALIZED_PROPERTY_VERSION. */
    int version;
    /** @brief   Whether this is a property the device reported (and we're seeing what IoT Hub last received from the device)
         or whether it's a writable property request from the device. */
    IOTHUB_CLIENT_PROPERTY_TYPE propertyType;
    /** @brief Name of the component.  Optional; may be NULL for the root component. */
    const char* componentName;
    /** @brief Name of the property. */
    const char* name;
    /** @brief Value of the property. */
    const char* value;
    size_t valueLength;
} IOTHUB_CLIENT_DESERIALIZED_PROPERTY;



/**
* @brief   Serializes reported properties into a format for sending to IoT Hub.
*
* @param   properties                  Pointer to IOTHUB_CLIENT_REPORTED_PROPERTY to be serialized.
* @param   numProperties               Number of elements contained in @c properties.
* @param   componentName               Optional component name these properties are part of.  May be NULL for default component.
* @param   serializedProperties        Serialized output of @c properties for sending to IoT Hub.
                                       The application must release this memory using free().
*                                      Note: This is NOT a \0 terminated string.
* @param   serializedPropertiesLength  Length of serializedProperties.
*
* @remarks  Applications can also manually construct the payload based on the convention rules.  This API is an easier to use 
*           alternative, so the application can use the more convenient IOTHUB_CLIENT_REPORTED_PROPERTY structure instead of raw serialization.
* 
*           This API does not perform any network I/O.  It only translates IOTHUB_CLIENT_REPORTED_PROPERTY into a byte array.  Applications
*           should use APIs such as IoTHubDeviceClient_LL_SendPropertiesAsync to send the serialized data.
* 
* @return   IOTHUB_CLIENT_OK upon success or an error code upon failure.
*/
IOTHUB_CLIENT_RESULT IoTHubClient_Serialize_ReportedProperties(
    const IOTHUB_CLIENT_REPORTED_PROPERTY* properties, 
    size_t numProperties, 
    const char* componentName, 
    unsigned char** serializedProperties, 
    size_t* serializedPropertiesLength); // TODO - transition to handle based.

/**
* @brief   Serializes the response to writeable properties into a format for sending to IoT Hub.  
*
* @param   properties                  Pointer to IOTHUB_CLIENT_WRITEABLE_PROPERTY_RESPONSE to be serialized
* @param   numProperties               Number of elements contained in @c properties.
* @param   componentName               Optional component name these properties are part of.  May be NULL for default component.
* @param   serializedProperties        Serialized output of @c properties for sending to IoT Hub.
                                       The application must release this memory using free().
*                                      Note: This is NOT a \0 terminated string.
* @param   serializedPropertiesLength  Length of serializedProperties
* 
* @remarks  Applications typically will invoke this API when processing a property from service (IOTHUB_CLIENT_PROPERTIES_RECEIVED_CALLBACK)
            to indicate whether properties have been accepted or rejected by the device.  For example, if the service requested
*           DesiredTemp=50, then the application could fill out the fields in an IOTHUB_CLIENT_WRITEABLE_PROPERTY_RESPONSE structure indicating whether
*           the request can be processed or whether there was a failure.
*
*           Applications can also manually construct the payload based on the convention rules.  This API is an easier to use 
*           alternative, so the application can use the more convenient IOTHUB_CLIENT_WRITEABLE_PROPERTY_RESPONSE structure instead of raw serialization.
*
*           This API does not perform any network I/O.  It only translates IOTHUB_CLIENT_WRITEABLE_PROPERTY_RESPONSE into a byte array.  Applications
*           should use APIs such as IoTHubDeviceClient_LL_SendPropertiesAsync to send the serialized data.
*
* @return   IOTHUB_CLIENT_OK upon success or an error code upon failure.
*/
IOTHUB_CLIENT_RESULT IoTHubClient_Serialize_WriteablePropertyResponse(
    const IOTHUB_CLIENT_WRITEABLE_PROPERTY_RESPONSE* properties,
    size_t numProperties,
    const char* componentName,
    unsigned char** serializedProperties,
    size_t* serializedPropertiesLength);

typedef struct IOTHUB_CLIENT_PROPERTY_CONTEXT_TAG* IOTHUB_CLIENT_PROPERTY_CONTEXT_HANDLE;

IOTHUB_CLIENT_RESULT IoTHubClient_Deserialize_Properties_CreateIterator(
    IOTHUB_CLIENT_PROPERTY_PAYLOAD_TYPE payloadType,
    const unsigned char* payLoad,
    size_t payLoadLength,
    const char** componentsInModel,
    size_t numComponentsInModel,
    IOTHUB_CLIENT_PROPERTY_CONTEXT_HANDLE* propertyContextHandle, // TODO this should be called an iterator
    int* propertiesVersion);

IOTHUB_CLIENT_RESULT IoTHubClient_Deserialize_Properties_GetNextComponent(
    IOTHUB_CLIENT_PROPERTY_CONTEXT_HANDLE propertyContextHandle,
    const char** componentName,
    bool* componentSpecified);

IOTHUB_CLIENT_RESULT IoTHubClient_Deserialize_Properties_GetNextProperty(
    IOTHUB_CLIENT_PROPERTY_CONTEXT_HANDLE propertyContextHandle,
    IOTHUB_CLIENT_DESERIALIZED_PROPERTY* property,
    bool* propertySpecified);

void IoTHubClient_Deserialize_Properties_DestroyProperty(
    IOTHUB_CLIENT_DESERIALIZED_PROPERTY* property);

void IoTHubClient_Deserialize_Properties_Destroy(
    IOTHUB_CLIENT_PROPERTY_CONTEXT_HANDLE propertyContextHandle);


/**
* @brief   Frees memory allocated by IoTHubClient_Deserialize_Properties.
*
* @param   properties                  Array of IOTHUB_CLIENT_DESERIALIZED_PROPERTY initially allocated by @c IoTHubClient_Deserialize_Properties.
* @param   numProperties               Number of array elements in @c properties.
* 
*/
void IoTHubClient_Deserialized_Properties_Destroy(
    IOTHUB_CLIENT_DESERIALIZED_PROPERTY* properties,
    size_t numProperties);

void IoTHubClient_Deserialize_Properties_End(IOTHUB_CLIENT_PROPERTY_CONTEXT_HANDLE propertyContextHandle);

void IoTHubClient_Deserialize_Properties_FreeProperty(
    IOTHUB_CLIENT_DESERIALIZED_PROPERTY* property);



#endif /* IOTHUB_CLIENT_PROPERTIES_H */
