/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";

const packageName = "dt10";
const packageVersion = "1.0.0";

export class IotHubGatewayServiceAPIs20190701PreviewContext extends msRest.ServiceClient {
  apiVersion: string;
  credentials: msRest.ServiceClientCredentials;

  /**
   * Initializes a new instance of the IotHubGatewayServiceAPIs20190701PreviewContext class.
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(apiVersion: string, credentials: msRest.ServiceClientCredentials, options?: Models.IotHubGatewayServiceAPIs20190701PreviewOptions) {
    if (apiVersion === null || apiVersion === undefined) {
      throw new Error('\'apiVersion\' cannot be null.');
    }
    if (credentials === null || credentials === undefined) {
      throw new Error('\'credentials\' cannot be null.');
    }

    if (!options) {
      options = {};
    }
    if(!options.userAgent) {
      const defaultUserAgent = msRest.getDefaultUserAgentValue();
      options.userAgent = `${packageName}/${packageVersion} ${defaultUserAgent}`;
    }

    super(credentials, options);

    this.baseUri = options.baseUri || this.baseUri || "https://fully-qualified-iothubname.azure-devices.net";
    this.requestContentType = "application/json; charset=utf-8";
    this.apiVersion = apiVersion;
    this.credentials = credentials;

  }
}
