/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { IotHubGatewayServiceAPIs20190701PreviewContext } from "./iotHubGatewayServiceAPIs20190701PreviewContext";

class IotHubGatewayServiceAPIs20190701Preview extends IotHubGatewayServiceAPIs20190701PreviewContext {
  // Operation groups
  digitalTwin: operations.DigitalTwin;

  /**
   * Initializes a new instance of the IotHubGatewayServiceAPIs20190701Preview class.
   * @param apiVersion Version of the Api. Must be 2019-07-01-preview
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(apiVersion: string, credentials: msRest.ServiceClientCredentials, options?: Models.IotHubGatewayServiceAPIs20190701PreviewOptions) {
    super(apiVersion, credentials, options);
    this.digitalTwin = new operations.DigitalTwin(this);
  }
}

// Operation Specifications

export {
  IotHubGatewayServiceAPIs20190701Preview,
  IotHubGatewayServiceAPIs20190701PreviewContext,
  Models as IotHubGatewayServiceAPIs20190701PreviewModels,
  Mappers as IotHubGatewayServiceAPIs20190701PreviewMappers
};
export * from "./operations";
