"use strict";
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
exports.__esModule = true;
var Models = require("./models");
exports.IotHubGatewayServiceAPIs20190701PreviewModels = Models;
var Mappers = require("./models/mappers");
exports.IotHubGatewayServiceAPIs20190701PreviewMappers = Mappers;
var operations = require("./operations");
var iotHubGatewayServiceAPIs20190701PreviewContext_1 = require("./iotHubGatewayServiceAPIs20190701PreviewContext");
exports.IotHubGatewayServiceAPIs20190701PreviewContext = iotHubGatewayServiceAPIs20190701PreviewContext_1.IotHubGatewayServiceAPIs20190701PreviewContext;
var IotHubGatewayServiceAPIs20190701Preview = /** @class */ (function (_super) {
    __extends(IotHubGatewayServiceAPIs20190701Preview, _super);
    /**
     * Initializes a new instance of the IotHubGatewayServiceAPIs20190701Preview class.
     * @param apiVersion Version of the Api. Must be 2019-07-01-preview
     * @param credentials Subscription credentials which uniquely identify client subscription.
     * @param [options] The parameter options
     */
    function IotHubGatewayServiceAPIs20190701Preview(apiVersion, credentials, options) {
        var _this = _super.call(this, apiVersion, credentials, options) || this;
        _this.digitalTwin = new operations.DigitalTwin(_this);
        return _this;
    }
    return IotHubGatewayServiceAPIs20190701Preview;
}(iotHubGatewayServiceAPIs20190701PreviewContext_1.IotHubGatewayServiceAPIs20190701PreviewContext));
exports.IotHubGatewayServiceAPIs20190701Preview = IotHubGatewayServiceAPIs20190701Preview;
__export(require("./operations"));
