"use strict";
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
exports.__esModule = true;
var mappers_1 = require("../models/mappers");
exports.DigitalTwinInterfaces = mappers_1.DigitalTwinInterfaces;
exports.InterfaceModel = mappers_1.InterfaceModel;
exports.Property = mappers_1.Property;
exports.Reported = mappers_1.Reported;
exports.DesiredState = mappers_1.DesiredState;
exports.Desired = mappers_1.Desired;
exports.DigitalTwinGetAllInterfacesHeaders = mappers_1.DigitalTwinGetAllInterfacesHeaders;
exports.DigitalTwinInterfacesPatch = mappers_1.DigitalTwinInterfacesPatch;
exports.DigitalTwinInterfacesPatchInterfacesValue = mappers_1.DigitalTwinInterfacesPatchInterfacesValue;
exports.DigitalTwinInterfacesPatchInterfacesValuePropertiesValue = mappers_1.DigitalTwinInterfacesPatchInterfacesValuePropertiesValue;
exports.DigitalTwinInterfacesPatchInterfacesValuePropertiesValueDesired = mappers_1.DigitalTwinInterfacesPatchInterfacesValuePropertiesValueDesired;
exports.DigitalTwinUpdateMultipleInterfacesHeaders = mappers_1.DigitalTwinUpdateMultipleInterfacesHeaders;
exports.DigitalTwinGetSingleInterfaceHeaders = mappers_1.DigitalTwinGetSingleInterfaceHeaders;
exports.DigitalTwinInvokeInterfaceCommandHeaders = mappers_1.DigitalTwinInvokeInterfaceCommandHeaders;
exports.DigitalTwinGetDigitalTwinModelHeaders = mappers_1.DigitalTwinGetDigitalTwinModelHeaders;
