"use strict";
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
exports.__esModule = true;
exports.DesiredState = {
    serializedName: "DesiredState",
    type: {
        name: "Composite",
        className: "DesiredState",
        modelProperties: {
            code: {
                serializedName: "code",
                type: {
                    name: "Number"
                }
            },
            subCode: {
                serializedName: "subCode",
                type: {
                    name: "Number"
                }
            },
            version: {
                serializedName: "version",
                type: {
                    name: "Number"
                }
            },
            description: {
                serializedName: "description",
                type: {
                    name: "String"
                }
            }
        }
    }
};
exports.Reported = {
    serializedName: "Reported",
    type: {
        name: "Composite",
        className: "Reported",
        modelProperties: {
            value: {
                serializedName: "value",
                type: {
                    name: "Object"
                }
            },
            desiredState: {
                serializedName: "desiredState",
                type: {
                    name: "Composite",
                    className: "DesiredState"
                }
            }
        }
    }
};
exports.Desired = {
    serializedName: "Desired",
    type: {
        name: "Composite",
        className: "Desired",
        modelProperties: {
            value: {
                serializedName: "value",
                type: {
                    name: "Object"
                }
            }
        }
    }
};
exports.Property = {
    serializedName: "Property",
    type: {
        name: "Composite",
        className: "Property",
        modelProperties: {
            reported: {
                serializedName: "reported",
                type: {
                    name: "Composite",
                    className: "Reported"
                }
            },
            desired: {
                serializedName: "desired",
                type: {
                    name: "Composite",
                    className: "Desired"
                }
            }
        }
    }
};
exports.InterfaceModel = {
    serializedName: "Interface",
    type: {
        name: "Composite",
        className: "InterfaceModel",
        modelProperties: {
            name: {
                serializedName: "name",
                type: {
                    name: "String"
                }
            },
            properties: {
                serializedName: "properties",
                type: {
                    name: "Dictionary",
                    value: {
                        type: {
                            name: "Composite",
                            className: "Property"
                        }
                    }
                }
            }
        }
    }
};
exports.DigitalTwinInterfaces = {
    serializedName: "DigitalTwinInterfaces",
    type: {
        name: "Composite",
        className: "DigitalTwinInterfaces",
        modelProperties: {
            interfaces: {
                serializedName: "interfaces",
                type: {
                    name: "Dictionary",
                    value: {
                        type: {
                            name: "Composite",
                            className: "InterfaceModel"
                        }
                    }
                }
            },
            version: {
                serializedName: "version",
                type: {
                    name: "Number"
                }
            }
        }
    }
};
exports.DigitalTwinInterfacesPatchInterfacesValuePropertiesValueDesired = {
    serializedName: "DigitalTwinInterfacesPatch_interfacesValue_propertiesValue_desired",
    type: {
        name: "Composite",
        className: "DigitalTwinInterfacesPatchInterfacesValuePropertiesValueDesired",
        modelProperties: {
            value: {
                serializedName: "value",
                type: {
                    name: "Object"
                }
            }
        }
    }
};
exports.DigitalTwinInterfacesPatchInterfacesValuePropertiesValue = {
    serializedName: "DigitalTwinInterfacesPatch_interfacesValue_propertiesValue",
    type: {
        name: "Composite",
        className: "DigitalTwinInterfacesPatchInterfacesValuePropertiesValue",
        modelProperties: {
            desired: {
                serializedName: "desired",
                type: {
                    name: "Composite",
                    className: "DigitalTwinInterfacesPatchInterfacesValuePropertiesValueDesired"
                }
            }
        }
    }
};
exports.DigitalTwinInterfacesPatchInterfacesValue = {
    serializedName: "DigitalTwinInterfacesPatch_interfacesValue",
    type: {
        name: "Composite",
        className: "DigitalTwinInterfacesPatchInterfacesValue",
        modelProperties: {
            properties: {
                serializedName: "properties",
                type: {
                    name: "Dictionary",
                    value: {
                        type: {
                            name: "Composite",
                            className: "DigitalTwinInterfacesPatchInterfacesValuePropertiesValue"
                        }
                    }
                }
            }
        }
    }
};
exports.DigitalTwinInterfacesPatch = {
    serializedName: "DigitalTwinInterfacesPatch",
    type: {
        name: "Composite",
        className: "DigitalTwinInterfacesPatch",
        modelProperties: {
            interfaces: {
                serializedName: "interfaces",
                type: {
                    name: "Dictionary",
                    value: {
                        type: {
                            name: "Composite",
                            className: "DigitalTwinInterfacesPatchInterfacesValue"
                        }
                    }
                }
            }
        }
    }
};
exports.DigitalTwinGetAllInterfacesHeaders = {
    serializedName: "digitaltwin-getallinterfaces-headers",
    type: {
        name: "Composite",
        className: "DigitalTwinGetAllInterfacesHeaders",
        modelProperties: {
            eTag: {
                serializedName: "etag",
                type: {
                    name: "String"
                }
            }
        }
    }
};
exports.DigitalTwinUpdateMultipleInterfacesHeaders = {
    serializedName: "digitaltwin-updatemultipleinterfaces-headers",
    type: {
        name: "Composite",
        className: "DigitalTwinUpdateMultipleInterfacesHeaders",
        modelProperties: {
            eTag: {
                serializedName: "etag",
                type: {
                    name: "String"
                }
            }
        }
    }
};
exports.DigitalTwinGetSingleInterfaceHeaders = {
    serializedName: "digitaltwin-getsingleinterface-headers",
    type: {
        name: "Composite",
        className: "DigitalTwinGetSingleInterfaceHeaders",
        modelProperties: {
            eTag: {
                serializedName: "etag",
                type: {
                    name: "String"
                }
            }
        }
    }
};
exports.DigitalTwinInvokeInterfaceCommandHeaders = {
    serializedName: "digitaltwin-invokeinterfacecommand-headers",
    type: {
        name: "Composite",
        className: "DigitalTwinInvokeInterfaceCommandHeaders",
        modelProperties: {
            xMsRequestId: {
                serializedName: "x-ms-request-id",
                type: {
                    name: "String"
                }
            },
            xMsCommandStatuscode: {
                serializedName: "x-ms-command-statuscode",
                type: {
                    name: "Number"
                }
            }
        }
    }
};
exports.DigitalTwinGetDigitalTwinModelHeaders = {
    serializedName: "digitaltwin-getdigitaltwinmodel-headers",
    type: {
        name: "Composite",
        className: "DigitalTwinGetDigitalTwinModelHeaders",
        modelProperties: {
            eTag: {
                serializedName: "etag",
                type: {
                    name: "String"
                }
            },
            xMsModelId: {
                serializedName: "x-ms-model-id",
                type: {
                    name: "String"
                }
            }
        }
    }
};
