"use strict";
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
exports.__esModule = true;
exports.apiVersion = {
    parameterPath: "apiVersion",
    mapper: {
        required: true,
        serializedName: "api-version",
        type: {
            name: "String"
        }
    }
};
exports.commandName = {
    parameterPath: "commandName",
    mapper: {
        required: true,
        serializedName: "commandName",
        type: {
            name: "String"
        }
    }
};
exports.connectTimeoutInSeconds = {
    parameterPath: [
        "options",
        "connectTimeoutInSeconds"
    ],
    mapper: {
        serializedName: "connectTimeoutInSeconds",
        type: {
            name: "Number"
        }
    }
};
exports.digitalTwinId = {
    parameterPath: "digitalTwinId",
    mapper: {
        required: true,
        serializedName: "digitalTwinId",
        type: {
            name: "String"
        }
    }
};
exports.expand = {
    parameterPath: [
        "options",
        "expand"
    ],
    mapper: {
        serializedName: "expand",
        defaultValue: false,
        type: {
            name: "Boolean"
        }
    }
};
exports.ifMatch = {
    parameterPath: [
        "options",
        "ifMatch"
    ],
    mapper: {
        serializedName: "If-Match",
        type: {
            name: "String"
        }
    }
};
exports.interfaceName = {
    parameterPath: "interfaceName",
    mapper: {
        required: true,
        serializedName: "interfaceName",
        type: {
            name: "String"
        }
    }
};
exports.modelId = {
    parameterPath: "modelId",
    mapper: {
        required: true,
        serializedName: "modelId",
        type: {
            name: "String"
        }
    }
};
exports.responseTimeoutInSeconds = {
    parameterPath: [
        "options",
        "responseTimeoutInSeconds"
    ],
    mapper: {
        serializedName: "responseTimeoutInSeconds",
        type: {
            name: "Number"
        }
    }
};
