name: "Set Issue Label"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@596dfb92b8ba81449d4b3a0f34e9d3d279fab330 # v1.0.0
        with:
          keywords: '[""]'
          labels: '["IoTSDK"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
